### ISSUE TITLE
States with the name 'pass' cause chart execution syntax error

### ISSUE THREAD

**Issue by alexzhornyak** [aleph2c/miros-xml#1]
Hi, I'm trying to execute any of W3C tests but I've got a syntax error while executing it. The problem is with the state **'pass'**

![image](https://user-images.githubusercontent.com/18611095/112189356-9ad3cc80-8c0c-11eb-958e-5a8aacc25048.png)
```xml
<scxml datamodel="python" initial="s0" name="ScxmlTest144" version="1.0" xmlns="http://www.w3.org/2005/07/scxml" xmlns:conf="http://www.w3.org/2005/scxml-conformance">
	<state id="s0">
		<onentry>
			<raise event="foo"/>
			<raise event="bar"/>
		</onentry>
		<transition event="foo" target="s1"/>
		<transition event="*" target="_fail"/>
	</state>
	<state id="s1">
		<transition event="bar" target="pass"/>
		<transition event="*" target="_fail"/>
	</state>
	<final id="pass">
		<onentry>
			<log expr="'pass'" label="Outcome"/>
		</onentry>
	</final>
	<final id="_fail">
		<onentry>
			<log expr="'fail'" label="Outcome"/>
		</onentry>
	</final>
</scxml>
```

```
Traceback (most recent call last):
  File "miros-xml-master\test\test_lib_.py", line 21, in <module>
    ao = xml_to_chart.make()
  File "miros-xml-master\miros_scxml\xml_to_miros.py", line 762, in make
    exec("from {module_name} import {statename} as ScxmlChart".format(
  File "<string>", line 1, in <module>
  File "test144_.py", line 73
    status = self.trans(pass)
                        ^
SyntaxError: invalid syntax
```

P.S. I've seen in your examples that you are renaming it to '_pass' and I can confirm that it is working if do the same

**Could you explain is this the bug or feature? I haven't seen any info in docs about state naming restrictions**

**Comment by aleph2c** [comment]
pass is a keyword in Python, so you can't use it as a variable/class/state name.

**Comment by alexzhornyak** [comment]
Thank you for explanation. I would recommend to mention about it in [List of exceptions to the SCXML Standard](https://github.com/aleph2c/miros-xml#list-of-exceptions-to-the-scxml-standard). Because according to standard the name of state may be any valid XML Schema name.

**Comment by aleph2c** [comment]
I have updated the list of exceptions based on this recommendation.
